Add test data aldiuk
q-m/food-nutrient-parser-python pull request #1
Opened 2023-04-04 12:52 UTC by WPDOrdina

Added test data for nutrient information and test data for html from AldiUK containing nutrient information

2023-04-05 07:37 UTC, wvengen approved these changes
Super, thanks!

2023-04-05 08:09 UTC, wvengen requested changes
Ah, btw, let's only do the text version here.

At this moment, the table parser expects nutrients formatted in html, not as text-in-html. For our first use of this module, I would think that a spider extracts the nutrient text, and uses the text parser. Later we could consider recognizing text-based nutrients in html.

Could you open an issue for recognizing text-based nutrients in html, add add the html example here? That is something for the future.

2023-04-06 08:18 UTC, WPDOrdina commented
Sure! I removed the commit with HTML from this PR and created a ticket for future use

2023-04-06 12:10 UTC, wvengen approved these changes

2023-04-06 12:10 UTC, merged